### PR TITLE
Fixed not working filtering in function 'getPlugins()'

### PR DESCRIPTION
**Pull request by lpaulsen93**
- separate placeholders with ```,``` and enclose strings in ```'```
- fixed ambiguous use of column ```plugin``` (a column named ```plugin``` exists in both tables)
- make sure that the values passed to ```$stmt->execute``` are equal to the referenced values in ```$sql```

### CODE REVIEW

**Comment by lpaulsen93** [comment]
Not sure if that is the problem described in https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/pull/96 but it was a problem that I encountered in my tests.

**Comment by Klap-in** [comment]
Which of these three fixes the issue? the 2nd?

**Comment by lpaulsen93** [comment]
I would say all.

I debugged the problem in the following way:
- I dumped the SQL string via the ```msg()``` function
- I replaced the bound values manually (```:plugin_tag``` and ```:plugin_type```)
- I entered the result in the mysql console and see what happens

Only if I apply all 3 changes the mysql console will accept the input and perform the query. If only one was missing then I got an error. Seen from the syntax perspective it seems to be three errors.

**Comment by lpaulsen93** [comment]
If you only apply the first two, then the SQL statement in ```$sql``` is correct but it still does not work. See http://php.net/manual/de/pdostatement.execute.php:

> # input_parameters
>
>    An array of values with as many elements as there are bound parameters in the SQL statement being executed. All values are treated as PDO::PARAM_STR.
>
>    Multiple values cannot be bound to a single parameter; for example, it is not allowed to bind two values to a single named parameter in an IN() clause.
>
>   Binding more values than specified is not possible; if more keys exist in input_parameters than in the SQL specified in the PDO::prepare(), **then the statement will fail and an error is emitted**.

**Comment by Klap-in** [comment]
Lars, Thanks for your effort and contribution. I have improved my PR with with your examples and cases. I have tried to simplify the query generation as well. As I have reworked the code therefore I will not merge this PR.

**Comment by lpaulsen93** [comment]
:thumbsup: Thanks. Fine for me.

**Pull request closed without merging**
